apiVersion: v1
kind: Service
metadata:
  name: service 
  namespace: deployment
spec:
  selector:
    app: python-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
